### ISSUE TITLE
Grade assignments do not match with visual inspection of BINs and species

### ISSUE THREAD

**Issue by paulapappalardo** [tadeu95/BAGS#2] opened 2021-12-03 00:06 UTC
Hi, first thank you so much for creating such an awesome tool! I have been playing with it downloading data for marine pteropods (tax filter Pteropoda, filter for marine species). I was surprised by the huge amount of sequences classified as **E**, so I started inspecting the data to understand why that would be the case. I discovered many sequences classified as **E** that do not have multiple species in the same BIN code, and also species classified as **C** that do have different species names for the same BIN number. It may be something that I am doing wrong or interpreting in the wrong way? Just in case I wanted to leave a comment. Here are the screenshots of a few summary tables to highlight the issue (also the summary tables), the data that I downloaded from BAGS for the pteropods (as .csv since I could not upload the .tsv), and also a slide where I copied the report for my download. Looking forward to your advice on this issue. Thank you. Paula

![BIN-tagged-as-C-with-different-species](https://user-images.githubusercontent.com/8711223/144521077-a8d106e2-3c8f-4120-b4d8-66f0c164b98b.jpg)
![samples-tagged-as-E](https://user-images.githubusercontent.com/8711223/144521078-096de91d-da18-4d5f-a186-1e643486abc8.jpg)
s
[BAGS_Pteropoda.csv](https://github.com/tadeu95/BAGS/files/7645801/BAGS_Pteropoda.csv)
[table-only-E-by-BIN.csv](https://github.com/tadeu95/BAGS/files/7645810/table-only-E-by-BIN.csv)
[table-all-grades-by-BIN.csv](https://github.com/tadeu95/BAGS/files/7645811/table-all-grades-by-BIN.csv)
![report-from-BAGS-website](https://user-images.githubusercontent.com/8711223/144522075-d14fc375-7fe6-4371-a94c-fa8bf3279ea2.jpg)

.

**Comment by tadeu95** [comment] 2021-12-03 01:34
Hello Paula,

Thank you so much for using the application and also for your feedback!

I'll try to clarify the issue you raised about the species classified as grade E:

The grade assignment in BAGS is performed at the species level, and therefore not at the level of BINs, records or sequences. So, grades are attributed to the species and not the BINs. 
Basically, BAGS classifies a species as grade E if, at a certain moment in time, that species has at least one record which shares a BIN with a record from another species. So, even if a species has records  included in a concordant BIN, that species still may be classified as grade E if, for instance, it is also has records attributed to another BIN containing records from multiple species.

Looking at your data, I can give you one example of this situation. For instance, Clione limacina has 3 different BINs at BOLD: BOLD:AAB2760; BOLD:AAB2761; and BOLD:AAB2762. 

As shown in your data set, BOLD:AAB2760 is a concordant BIN as it only includes Clione limacina records. However, as you can see in the images I attached below, BOLD:AAB2761 has 24 records of Clione limacina and 1 record of Clione elegantissima. Similarly, BOLD:AAB2762 has 4 records of Clione antarctica and 3 records of Clione limacina. According to the BAGS pipeline, these are classified as grade E. Regardless, don't be alarmed because many grade E scenarios may be caused by pseudo-discordances and not necessarily by actual incongruencies or errors (please checkTable 2 of the BAGS' paper, I'm attaching it below).


As for the grade C issue you raised, you are correct, BOLD:ACZ1440 at this moment has records from two different species, and both Creseis clava and Creseis acicula should be grade E according to the BAGS pipeline. 

I'll clarify:

What happens is that, in order to be as comprehensive as possible, the grade assigment performed by BAGS is based on all animal public records (with BINs) available at BOLD at a given time, and not just on the data present in a specific library/data set. 

In order to do that, we periodically download all the animal public data from BOLD, in order to calculate the number of BINs each species is attributed to; as well as the number of species that are included in each BIN (you can manually check this information in the two files present in the repository named "species_per_bin.txt" and "bins_per_species.txt"). 

However, BINs change periodically, so the results from BAGS at a given moment in time may not match the current information at BOLD. In your particular case, what happened is that at the time when we last downloaded all the animal records data, BOLD:ACZ1440 only included records from one species. Back then, both Creseis clava and Creseis acicula were in fact grade C, but not anymore. 

We try to update the files as soon as possible, but unfortunately the download speed at BOLD has decreased significantly in the past months, and so it has become more difficult to get the data needed to update the two files. We are hoping to make this update very soon, so all these situations should be rectified. 

Again, thank you for your feedback, if I wasn't clear about something please tell me. 

If anything else comes up please be free to tell us,

João Tadeu

![Screenshot_5](https://user-images.githubusercontent.com/52295127/144529003-0c1c6abc-2182-47f6-9746-cadeb7bf8f1e.png)

![Screenshot_4](https://user-images.githubusercontent.com/52295127/144529075-b8ce81a1-f9b9-45ab-ad18-350d735ed8bc.png)

**Comment by paulapappalardo** [comment] 2021-12-03 17:15
Thank you João for the clarifications. It seems my confusion was thinking from a BIN point of view, instead of a species point of view. Thinking about the taxonomic assignment, an example like the one you mentioned (Clione limacina) would not be as problematic, it could reveal cryptic diversity and point to a species that need further taxonomic revisions. I guess I would be more worried about the cases in which a BIN contains two species names because if those names are not synonyms, that points to a misidentification.
And thanks for explaining how the issue with the C assignment came to be. I completely understand the technical difficulties to have a "real-time" tool as the volume of information keeps increasing it is very hard to keep everything up to date. BAGS was surprisingly fast for the few groups I tried because of the current setup with the static database that gets updated every few months. So if I understood correctly you are saying that when we download from the BAGS shiny app we get the real-time BINS from BOLD, but the grade assignment algorithms are coded based on your most recent download from BOLD, and sometimes those two may have a few discrepancies. Please correct me if I understood wrong, or feel free to close this issue. And thank you for your prompt response. Cheers. Paula

**Comment by tadeu95** [comment] 2021-12-06 11:13
Hello Paula,

Exactly! One of our goals with BAGS is pinpointing species which might be holding cryptic diversity (especially the case of grade C species) or species needing taxonomic revision. Since there are many possible reasons for a grade E assignment, we hold the view that grade E should only serve as an incentive for a close examination or revision of that particular species' records, and not a conclusive sign of unrelieability. Ideally, we should manually observe each grade E species to try understand exactly what is happening.

That's correct, every time you download a new library, BAGS downloads the real time data from BOLD, including the BINs, sequences, species names, etc. Then, as you said, the code assigns the grades to each species previously compiled in the library, based on the information from our most recent download. 

For now I will close this issue, but If any other questions come along while you're using BAGS, please feel free to ask us! 

Cheers,
João Tadeu

**Closed as completed** 2021-12-07 12:40 UTC
